### ISSUE TITLE
Resolver errors not making it back to client

### ISSUE THREAD

**Issue by timchambers** [maticzav/graphql-middleware-sentry#14]
After installing this in my graphql-yoga server, errors that I throw in my resolvers are being reported to Sentry but no longer making it back to the client where I want to be able to handle them on the client side. I can't seem to figure out how to make that happen, is there a way to do so in the configuration options?

**Comment by maticzav** [comment]
Yea you are right, they are blocked by default. Hold my beer 🍺

**Comment by timchambers** [comment]
This is working brilliantly, thanks!

**Comment by juanignaciosl** [comment]
I'm getting this behavior in 3.2.1. This is my configuration:

```
    const sentryMiddleware = sentry({
      config: {
        dsn: CONFIG.SENTRY_DSN,
        environment: ENVIRONMENT
      },
      withScope: (scope, error, context) => {
        scope.setUser({
          id: context.user.auth0UserId,
          email: context.user.email
        })
        scope.setExtra('body', context.request.body)
        scope.setExtra('origin', context.request.headers.origin)
        scope.setExtra('user-agent', context.request.headers['user-agent'])
      }
    })
    middlewares.push(sentryMiddleware)
```

Commenting the last line makes this work.

**Comment by juanignaciosl** [comment]
Oh, `forwardErrors: true` options fixes it. I'd argue that a safer default would be better, but at least an explicit mention in the README might be welcomed :_)

Anyway, thanks for this module!
