### ISSUE TITLE
Migrate to '@sentry/node'

### ISSUE THREAD

**Issue by herkulano** [maticzav/graphql-middleware-sentry#29]
Sentry has deprecated Raven for `@sentry/node`.

https://docs.sentry.io/error-reporting/quickstart?platform=node

**Comment by maticzav** [comment]
Wow @herkulano, thank you for noticing this! 🙌 

Would you mind creating a PR as well? I am afraid I won't be able to push changes for about a month, therefore, your PR would come in really handy. Let me know if that's an option for you 🙂
