### ISSUE TITLE
forwardErrors does not seem to work (in combination with apollo-errors)

### ISSUE THREAD

**Issue by mfruhner** [maticzav/graphql-middleware-sentry#35]
Hi,
I just discovered your middleware and it looks really nice and easy to use.
However, the 'forwardErrors' option does not seem to work for me.
The errors are reported nicely in sentry.io, but the client always receives null.

Maybe this happens, because I try to use it alongside with 'apollo-errors' ? I am using this to format my errors in a readable and consistent way.

I am using this config:

```
const sentryMiddleware = sentry({
  dsn: process.env.SENTRY_DSN,
  config: {
    environment: process.env.NODE_ENV,
    release: process.env.npm_package_version,
    captureReturnedErrors: true,
    forwardErrors: true,
  },
  /* extras: [
    { name: 'body', path: 'request.body' },
    { name: 'origin', path: 'request.headers.origin' },
    { name: 'user-agent', path: "request.headers['user-agent']" },
  ], */
});
```

Thanks in advance,
Maik

**Comment by maticzav** [comment]
Hey @mfruhner could you verify that this is still an issue with the latest version?

**Comment by mfruhner** [comment]
Works great now!
Thanks!
